services:
    configserverms:
        image: chgvcode/configserverms:latest
        container_name: configserverms
        ports:
            - 8080:8080
        depends_on:
            - servicereg
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker
    servicereg:
        image: chgvcode/servicereg:latest
        container_name: servicereg
        ports:
            - "8761:8761"
        depends_on:
            - rabbitmq
            - zipkin
            - postgres
            - pgadmin4
        networks:
            - microservice-network
            - postgres
    companyms:
        image: chgvcode/companyms:latest
        container_name: companyms
        ports:
            - 8081:8081
        depends_on:
            - servicereg
            - configserverms
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker
    jobms:
        image: chgvcode/jobms:latest
        container_name: jobms
        ports:
            - 8082:8082
        depends_on:
            - servicereg
            - configserverms
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka
    reviewms:
        image: chgvcode/reviewms:latest
        container_name: reviewms
        ports:
            - 8083:8083
        depends_on:
            - servicereg
            - configserverms
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - microservice-network
            - postgres
    zipkin:
        image: openzipkin/zipkin
        container_name: zipkin
        ports:
            - 9411:9411
        networks:
            - microservice-network
            - postgres
    gatewayms:
        image: chgvcode/gatewayms:latest
        container_name: gatewayms
        ports:
            - 8085:8084
        networks:
            - microservice-network
            - postgres
        environment:
            - SPRING_PROFILES_ACTIVE=docker
    postgres:
        image: postgres
        container_name: postgres
        environment:
            - POSTGRES_USER=chgvcode
            - POSTGRES_PASSWORD=chgvcode
            - PGDATA=/data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - 5432:5432
        networks:
            - postgres
        restart: unless-stopped
    pgadmin4:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
            - PGADMIN_CONFIG_SERVER_MODE=False
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - 5050:80
        networks:
            - postgres
        restart: unless-stopped
networks:
    microservice-network:
        driver: bridge
    postgres:
        driver: bridge
volumes:
    postgres:
    pgadmin: